### ISSUE TITLE
Synchronize the new functionalities

### ISSUE THREAD

**Issue by rexromae** [ActivateMedia/Marsad#38]
- We have to synchronize all the changes done to the WordPress Marsad theme between the sites (Egypt - Libya - Palestine). All the new things are currently located in the Palestine version. 

- Install the new plugins

**Comment by manshanssen** [comment]
@rexromae this is now fully completed, correct?

**Comment by rexromae** [comment]
I would say yes. We have fully updated Marsad Egypt and Libya.
