### ISSUE TITLE
Master site for publications etc

### ISSUE THREAD

**Issue by manshanssen** [ActivateMedia/Marsad#53]
@gregrice we would like to use Marsad Egypt as the master site. However, could you first explain what would happen if we would need to close this site down. what would we need to do to ensure that the other ones continue to operate smoothly?

**Comment by manshanssen** [comment]
@rexromae could you confirm that Egypt now works as the master site and that all changes made on Egypt publications are transferred to the other marsad sites?

**Comment by rexromae** [comment]
Confirmed, Marsad Egypt is the master database for the publications. The API also bring the taxonomies attached to the pubs, so on Libya and Palestine the publications will be automatically tagged (actors, series, etc).

We need to setup an cron (auto) import; @manshanssen Do you think once a day would be enough to keep the websites updated?

**Comment by manshanssen** [comment]
@rexromae yes that should be enough

**Comment by rexromae** [comment]
@therealmyth can you please setup the 2 cron jobs on Marsad.ly?

once a day, in the night
http://marsad.ly/index.php?__api=1&import_publications=1
http://marsad.ly/index.php?__api=1&import_publications_thumbnails=1

Thanks
