### ISSUE TITLE
Social media

### ISSUE THREAD

**Issue by manshanssen** [ActivateMedia/Marsad#55]
Add all social media accounts to the auto-poster, Måns to send information to Andrea

**Comment by manshanssen** [comment]
@rexromae please dont activate the autoposting yet but insert all info and test it. 

Facebook: https://www.facebook.com/pages/Marsad-Palestinian-Security-Sector-Observatory/ 
the login and password is managed by the user jmana@gmx.ch which you shoudl have the password for already. This is the one that has access to all the marsad accounts

https://twitter.com/MarsadPalestine
user: j.rice@dcaf.ch
passw coming via skype

linkedin:
user j.rice@dcaf.ch
passw coming via skype

**Comment by rexromae** [comment]
**Facebook
A confirmation code was sent to +41 79 821 39 96. To confirm your identity, please enter the code here once it arrives.

**Twitter
Error
You must add your mobile phone to your Twitter profile before granting your application write capabilities. Please read https://support.twitter.com/articles/110250-adding-your-mobile-number-to-your-account-via-web for more information

@manshanssen

**Comment by manshanssen** [comment]
facebook should work now, working on Twitter

**Comment by rexromae** [comment]
Facebook has been configured and tested in the AutoPoster plugin. It works fine.

**Comment by manshanssen** [comment]
I cannot send emails to or from the info@marsad.ps address. could you check with fred if he could have a look at this?

**Comment by rexromae** [comment]
@therealmyth can you please look at this?

**Comment by manshanssen** [comment]
@rexromae twitter username: m.hanssen@dcaf.ch passw coming via skype

**Comment by rexromae** [comment]
@manshanssen can you please double check the twitter username and password? I couldn't access it. Thanks

**Comment by manshanssen** [comment]
@rexromae sorry username is j.rice@dcaf.ch

**Comment by rexromae** [comment]
I did the Twitter setup but it looks like there is an issue in the Write permissions on the account, I have checked and they are enabled. It could take hours to apply the changes to I will try tomorrow.

**Comment by manshanssen** [comment]
@rexromae anything you need from me in terms of this?

**Comment by rexromae** [comment]
@manshanssen No, for the moment. I did the setup of the Twitter account but apparently is not working because of this:

"Twitter is over capacity. Please wait a moment and try again."

it's a while that I'm trying and I get the same error. I will try a bit later.

**Comment by manshanssen** [comment]
@rexromae any news on if this is working now?

**Comment by rexromae** [comment]
Twitter has been configured correctly.

**Comment by manshanssen** [comment]
@rexromae so this issue is all taken care of for PAL correct?

**Comment by rexromae** [comment]
This issue is related to Marsad Palestine, correct.

**Comment by rexromae** [comment]
All the social media accounts have been setup correctly. (FB, TW, IN).
