### ISSUE TITLE
Slugs

### ISSUE THREAD

**Issue by manshanssen** [ActivateMedia/Marsad#59]
could you please go through the slugs on the site and make sure that they are applicable?

**Comment by rexromae** [comment]
"Civil Society" is an actor and theme as well. Could you rename one of them? The issue is, the slug can't be "civil-society" for both and the second slug is automatically set to "civil-society-2". This could cause 404 error. Thanks

**Comment by rexromae** [comment]
The same happens for the term "All" that is a "Type" and a "Governorate". If you could find 2 different versions of the term would be great.

I have checked all the terms and fixed the wrong slugs.

**Comment by manshanssen** [comment]
@rexromae done
