### ISSUE TITLE
Source in AR articles

### ISSUE THREAD

**Issue by manshanssen** [ActivateMedia/Marsad#61]
@rexromae most Arabic articles mention "source", could we do something about this?

**Comment by manshanssen** [comment]
almost every article contains this error, what would be needed to fix this with a script?

**Comment by rexromae** [comment]
To write, test and execute the script I estimate around 4 hours of work. I need this to be approved by you and @gregrice

**Comment by manshanssen** [comment]
@rexromae ok, we will have to wait with this one. We will be able to back and do it later on right?
