### ISSUE TITLE
Governorate translation

### ISSUE THREAD

**Issue by manshanssen** [ActivateMedia/Marsad#62]
@rexromae could you please make sure that the governorate translation is changed. it currently has two names in the hompage above the map. it should be only: المحافظة

**Comment by manshanssen** [comment]
@rexromae any news on this?

**Comment by rexromae** [comment]
I have recently added the 131 string manually and it works as expected

**Comment by manshanssen** [comment]
@rexromae the below image shows that the governorates map still has a double heading. 

![image](https://cloud.githubusercontent.com/assets/9803133/5660803/a29a351e-9724-11e4-9919-0744474f2cd2.png)

**Comment by rexromae** [comment]
I have changed it.
