### ISSUE TITLE
Timeline bug

### ISSUE THREAD

**Issue by manshanssen** [ActivateMedia/Marsad#66]
@rexromae I just noted that the whole of 2014 is empty on the timeline (for the "all" process) although we have a lot of posts for this year. Could you look into this please?

**Comment by rexromae** [comment]
I have created a 'March test' dated March 2014, tagged as 'Cairo Donor Conference' and it appears correctly in the Timeline.

Can you give me some examples of Posts tagged as Events not displayed in the Timeline?

**Comment by manshanssen** [comment]
@rexromae ok I guess they just screwed up the tagging during this period then...strange though. You can remove the test.
