### ISSUE TITLE
domain URL

### ISSUE THREAD

**Issue by manshanssen** [ActivateMedia/Marsad#67]
@rexromae I just noted that the www.marsad-libya.info address is not working, could you look into this please?

**Comment by rexromae** [comment]
Sorry Mans, I must have missed the GitHub notification. This kind of issues should be referenced to our sys admin Fred. @therealmyth Can you look into this, please?

**Comment by therealmyth** [comment]
Hi Mans, the domain has been setup and should start working as soon as the DNS config propagate.
