### ISSUE TITLE
Facebook auto-post

### ISSUE THREAD

**Issue by manshanssen** [ActivateMedia/Marsad#70]
@rexromae the auto-post to facebook doesnt seem to work. The page where posts should go is this one: https://www.facebook.com/pages/Marsad-Palestinian-Security-Sector-Observatory/ 

could you look into this please?

**Comment by rexromae** [comment]
I have done the setup for the new page. Tested and it works. I have disabled the plugin until we go live in order to avoid links to the test site, that will generate confusion, especially for Google that would start indexing the test-site.
