### ISSUE TITLE
MARSAD LIBYA IS DOWN

### ISSUE THREAD

**Issue by manshanssen** [ActivateMedia/Marsad#71]
@rexromae @gregrice Marsad Libya is not loading.

**Comment by manshanssen** [comment]
@rexromae @gregrice Marsad Libya is down again.

**Comment by manshanssen** [comment]
@rexromae @gregrice now it is back...

**Comment by gregrice** [comment]
@therealmyth - can you have a  look at the stats on this to see if we can figure out why this one is getting overloaded.

**Comment by manshanssen** [comment]
@rexromae any feedback on this?

**Comment by rexromae** [comment]
This issue is related to this https://github.com/ActivateMedia/Marsad/issues/80

Let's keep just 1 opened.
