### ISSUE TITLE
Arabic Translation Needed

### ISSUE THREAD

**Issue by rexromae** [ActivateMedia/Marsad#73]
In view of the Palestine update on Monday, we are tying to ensure everything goes well in both short and long term. We are still working in order to make all the old URLs valid/reachable on the new website and  we have also improved the 404 error page. This page will handle all the broken links. We would need the arabic translation of the following text:

SORRY THIS PAGE DOES NOT EXIST
It seems that the resource you were looking for is not longer available or it has been moved.
Please start again from the homepage or try using the search box below.
[Search]
or... Go to the Homepage

Example:
http://test.marsad.info/en/this-page-does-not-exist

Thanks @manshanssen

**Comment by manshanssen** [comment]
@rexromae I have sent this to my colleagues and hope to get an answer before they leave the office

**Comment by manshanssen** [comment]
@rexromae I sent it to you via email

**Comment by rexromae** [comment]
Thanks @manshanssen! The page has been translated.
