### ISSUE TITLE
Footer issue

### ISSUE THREAD

**Issue by manshanssen** [ActivateMedia/Marsad#74]
@rexromae I just noted that the footer looks a bit funny:
![image](https://cloud.githubusercontent.com/assets/9803133/6776296/02090bd6-d13d-11e4-8c77-660acf357f85.png)

could you look into this please? 

In addition the email in the footer is for Egypt and should be changed to palestine, it should be info@marsad.ps

**Comment by rexromae** [comment]
Which OS/browser are you using? I can't see this issue on my screen

**Comment by manshanssen** [comment]
@rexromae I am using google chrome

**Comment by rexromae** [comment]
Are you using mac?

**Comment by manshanssen** [comment]
windows

**Comment by rexromae** [comment]
Can you please try to refresh you browser? Cleaning cache and restarting it.

**Comment by manshanssen** [comment]
the problem is still there
