### ISSUE TITLE
Publication section on Marsad Palestine

### ISSUE THREAD

**Issue by manshanssen** [ActivateMedia/Marsad#77]
@rexromae the publication section on marsad palestine is not up to date with the Egypt one. Could you look into this please? The last publication is missing, it was added a few weeks ago...

**Comment by rexromae** [comment]
Hi Mans, sorry but I forgot to switch on the auto-import on the live site. I have already run an import so it should be updated right now plus I've enabled the 12h auto-import for the next publications. Thanks!
