### ISSUE TITLE
Marsad Palestine: Source name and source link

### ISSUE THREAD

**Issue by manshanssen** [ActivateMedia/Marsad#81]
@rexromae the source name and source link fields are not working. we have tried to input the following information
source name: The Guardian 
source link: http://www.theguardian.com/world/2015/mar/20/jerusalem-at-boiling-point-of-polarisation-and-violence-eu-report

on this post: http://www.marsad.info/wp-admin/post.php?post=25582&action=edit&message=1

but to no success, could you look into this please?

**Comment by rexromae** [comment]
The problem is again related to Ceceppa Multilingua.. The plugin goes deep into the system and 3rd party plugins functionalities so it's easy for it to break things.

I'm still looking for a solution, I will need to enable the maintenance mode for few seconds / couple of mins maximum.

**Comment by rexromae** [comment]
What happen is, the Ceceppa plugin is in conflict with the custom fields plugin, it doesn't allow to save them, so I have temporary disabled Ceceppa, did some tests (saving, deleting) and the custom fields work perfectly, but we can't switch off Ceceppa, until we fix the problem, you can manually change the source_name and source_link from the custom fields standard editor. If they are not displayed in the dropdown, you have to Add New, type "source_name" or "source_link" and the value. This is a temp fix, until we find a final solution.

Thanks @manshanssen

**Comment by manshanssen** [comment]
@rexromae ok

**Comment by manshanssen** [comment]
@rexromae the user s.yassmine cannot see the costum fields, could you amend this please?

**Comment by rexromae** [comment]
@manshanssen I have checked with an account with the Editor role and they are there. I can't login with her account because I don't have her password but it should be enough to check if the Custom Fields section is enabled. 

* Click on **Screen Options** at the top of the page
* Verify that Custom Fields is checked

In case this does not work, I would need to test with that specific account.
