### ISSUE TITLE
Autopost LinkedIn not working

### ISSUE THREAD

**Issue by manshanssen** [ActivateMedia/Marsad#85]
@rexromae The autoposter from Marsad Egypt (and probably Libya and Palestine) are not working. it says access token expired.

**Comment by rexromae** [comment]
@manshanssen the LinkedIn password that I have it's not longer working. Can you please provide me access to your accounts?

**Comment by manshanssen** [comment]
sent via skype

**Comment by rexromae** [comment]
Egypt and Libya have been refreshed. Palestine will come in the next hours.

**Comment by rexromae** [comment]
They have been all fixed.
