### ISSUE TITLE
Facebook Marsad EG - Page not found issue

### ISSUE THREAD

**Issue by ciliadefrance** [ActivateMedia/Marsad#87]
@rexromae Posts on the Facebook page of Marsad EG include a "Page not found" notification. Clicking on the post first brings you to a 404 error page and then, after a few seconds, to the article.Could you please look into this?

**Comment by rexromae** [comment]
Hi @ciliadefrance, this issue has been already submitted to GitHub. Please have a look at this issue https://github.com/ActivateMedia/Marsad/issues/64
